#!/usr/local/bin/bash


#
# Location of base16 shell files.
#
BASE16_PATH="$HOME/programs/shell/base16-shell"

#
# Location of config file.
#
CONFIG_FILE="$COLOR_PATH/config"

#
# List all the available colors in the format
# color - background
# Color names correspond to their shell files in $BASE16_PATH
#
function list_all()
{
    scheme_files="${BASE16_PATH}/*.sh"

    echo
    echo "Available Color Schemes With Background"
    echo
    for file in $scheme_files
    do
        echo -e $file | sed "s#${BASE16_PATH}/base16-\([^.]*\).\(.*\).sh#\\1 - \\2#"
    done | column
}

#
# Prints an help on who to use the script.
#
function color_help()
{
    echo -e "color"
    echo "Change the base16 shell colors to any of the available colors with single command"
    echo "Basic Usage"
    echo -e "\t$ color scheme background"
    echo "List all colors"
    echo -e "\t$ color list"
    echo 
} 

#
# Creates new config file.
function new_config()
{
    echo '#!/usr/local/bin/bash 

# 
# Config file for color, saves the current 
# BACKGROUND and current color SCHEME. 
# This file will be auto generated by color.
# This file can also be manually created in the format,
# BACKGROUND="dark"
# SCHEME="tomorrow"
#

BACKGROUND="dark"
SCHEME="tomorrow"' > $CONFIG_FILE
 
}

#
# Sources the base 16 scheme file based on the current 
# SCHEME and BACKGROUND values.
#
function source_base16()
{
    base16_file="${BASE16_PATH}/base16-${SCHEME}.${BACKGROUND}.sh"
    if [[ -f "$base16_file" ]]
    then
        source "$base16_file"
        return 0
    fi
    return 1
}


#
# Updates the current config file with
# new SCHEME and BACKGROUND
#
function update_config()
{
    gsed -i "/BACKGROUND/ s/=.*/=\"$BACKGROUND\"/; \
        /SCHEME/ s/=.*/=\"$SCHEME\"/" "$CONFIG_FILE"
}


#
# Runs sanitiy checks for the existance of
# COLOR_PATH Required for config path location.
# BASE16_PATH 
#
function sanity_checks()
{
    if [[ -z $COLOR_PATH ]]
    then
        echo "COLOR_PATH is not configured correctly"
        return 1
    fi

    if [[ ! -d $BASE16_PATH ]]
    then
        echo "Base16 not found at  $BASE16_PATH"
        return 1
    fi
    return 0
}

#
# Load the current color schemes from config file.
#
function load_color()
{
    source "$CONFIG_FILE"
    source_base16
    return 0
}

#
# Entry script to color.
#
function color()
{
    
    sanity_checks
    if [[ $? -eq 1 ]] 
    then
        return 1
    fi


    if [[ ! -f "$CONFIG_FILE" ]]
    then
        echo "Cannot find config file. Creating new one."
        new_config
    fi

    source "$CONFIG_FILE"

    #
    # List the colors if the first argument is list.
    #
    if [[ $1 == "list" ]]
    then
        list_all
        return 0
    elif [[ $1 == "help" ]]
    then
        color_help
        return 0
    elif [[ $# -eq 1 ]] 
    then
        SCHEME="$1"
    elif [[ $# -eq 2 ]]
    then
        SCHEME="$1"
        BACKGROUND="$2"
    else
        # 
        # Prints the current scheme and background if nothing is specified.
        #
        echo "Current Scheme : $SCHEME"
        echo "Current Background : $BACKGROUND"
        return 0
    fi

    source_base16
    if [[ $? -eq 0 ]]
    then
        update_config
    else
        echo "Unknown scheme or background"
        list_all
    fi 
}
